---
- name: "Add elixir repo key to apt"
  apt_key:
    url: "https://packages.erlang-solutions.com/debian/erlang_solutions.asc"
  become: yes

- name: "Add erlang repository to apt"
  apt_repository:
    repo: deb https://packages.erlang-solutions.com/debian buster contrib
    state: present
  become: yes

- name: "Install elixir"
  apt:
    pkg: 
      - esl-erlang 
      - elixir
    state: present
    install_recommends: no
    update_cache: yes
  become: yes
