---
# Install firefox from tarball

- name: "Create tmp folder"
  tempfile:
    state: directory
    suffix: temp
  register: firefox_tmp_folder

- name: "Download firefox"
  get_url:
    url: "{{ firefox_url }}"
    dest: "{{ firefox_tmp_folder.path }}/{{ firefox_filename }}"
    checksum: "{{ firefox_sha256 }}"

- name: "Unpack firefox"
  unarchive:
    src: "{{ firefox_tmp_folder.path }}/{{ firefox_filename }}"
    dest: "/opt/"
    remote_src: yes
  become: yes

- name: "Add desktop file"
  template:
    src: firefox.desktop.j2
    dest: "{{ firefox_desktop_path }}/firefox.desktop"
  become: yes

- name: "Add firefox as x-www-browser"
  command: "update-alternatives --install /usr/bin/x-www-browser x-www-browser /opt/firefox/firefox 200"
  become: yes

- name: "Add firefox as default browser"
  command: "update-alternatives --set x-www-browser /opt/firefox/firefox"
  become: yes

- name: "Cleanup"
  file:
    path: "{{ firefox_tmp_folder.path }}"
    state: absent
  when: firefox_tmp_folder.path is defined
