---
# Playbook: Base config
# This will configure the base system packages, assets and keys

- hosts: all 
  ignore_unreachable: yes

  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: base
      when: ansible_facts['os_family'] == "Darwin"
    - role: base
      tags: base
    - role: bitwarden
      tags: bitwarden
    - role: keys
      tags: keys
    - role: yadm
      tags: yadm
    - role: vim
      tags: vim
    - role: fish
      tags: fish
#    - role: sshd
#      tags: sshd

- hosts: debdellorso
  roles:
    - role: wifi
      tags: network,wifi
    - role: 4k
      tags: 4k

- hosts: polobeardeb, debdellorso
  roles:
    - role: firmware
      tags: firmware

- hosts: Melorso
  tasks:
    - name: "Enable locate db"
      command: "launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist"
      become: yes
