---
# Playbook: Base config
# This will configure the base system packages, assets and secrets

- hosts: workstations
  roles:
    - role: base
      tags: base
    - role: fish
      tags: fish
    - role: yadm
      tags: yadm
