---
# Playbook: Base config
# This will configure the base system packages, assets and keys

- hosts: all 
  ignore_unreachable: yes
  roles:
    - role: base
      tags: base
    - role: keys
      tags: keys
    - role: yadm
      tags: yadm
    - role: vim
      tags: vim
    - role: fish
      tags: fish
    - role: sshd
      tags: sshd

- hosts: debdellorso
  roles:
    - role: wifi
      tags: base,network,wifi

- hosts: polobeardeb, debdellorso
  roles:
    - role: firmware
      tags: base,firmware
