---
# Playbook: Base config
# This will configure the base system packages, assets and keys

- hosts: all 
  ignore_unreachable: yes

  pre_tasks:
    - name: Set OS facts
      set_fact: OS="Darwin"

    - name: Test OS
      debug:
        msg: "THE OS IS {{OS}}"

    - name: Ansible Facts
      debug:
        msg: "{{ ansible_facts }}"

  roles:
    - role: base
      tags: base
      when: OS == 'Linux"
#    - role: bitwarden
#      tags: bitwarden
#    - role: keys
#      tags: keys
#    - role: yadm
#      tags: yadm
#    - role: vim
#      tags: vim
#    - role: fish
#      tags: fish
#    - role: sshd
#      tags: sshd

- hosts: debdellorso
  roles:
    - role: wifi
      tags: network,wifi
    - role: 4k
      tags: 4k

- hosts: polobeardeb, debdellorso
  roles:
    - role: firmware
      tags: firmware
