---
# Playbook: Base config
# This will configure the base system packages, assets and keys

- hosts: workstations
  roles:
    - role: base
      tags: base
    - role: keys
      tags: keys
    - role: yadm
      tags: yadm
    - role: fish
      tags: fish

- hosts: POLOBEAR-DEB
  roles:
    - role: firmware
      tags: base,firmware
