---
# Playbook: Base config
# This will configure the base system packages, assets and keys

- hosts: all 
  ignore_unreachable: yes
  roles:
    - role: base
      tags: base
    - role: keys
      tags: keys
    - role: yadm
      tags: yadm
    - role: fish
      tags: fish
    - role: sshd
      tags: sshd

- hosts: POLOBEAR-DEB
  roles:
    - role: firmware
      tags: base,firmware
