---
# Playbook: desktop environment
# This will configure X, i3 and all the apps necessary

- import_playbook: base_confs.yml

- hosts: workstations
  ignore_unreachable: yes
  roles:
    - role: X11
      tags: X11
    - role: lightdm
      tags: lightdm
    - role: i3wm
      tags: i3wm
    - role: polybar
      tags:
        - i3wm
        - polybar
    - role: fonts
      tags: fonts
    - role: sound
      tags: sound
    - role: firefox
      tags: 
        - apps
        - firefox
    - role: slack
      tags: 
        - apps
        - slack
    - role: spotify
      tags: 
        - apps
        - spotify
    - role: zoom
      tags:
        - apps
        - zoom
    - role: packer
      tags:
        - dev
        - packer
    - role: python
      tags:
        - python
        - dev
    - role: elixir
      tags:
        - dev
        - elixir
    - role: docker
      tags:
        - docker
        - dev
    - role: k8s-utils
      tags:
        - k8s
        - dev
    - role: terraform
      tags:
        - terraform
        - dev
    - role: hugo
      tags:
        - hugo
        - dev
