---
# Playbook: desktop environment
# This will configure X, i3 and all the apps necessary

- import_playbook: base_confs.yml

- hosts: workstations
  roles:
    - role: xorg
      tags: xorg
    - role: lightdm
      tags: lightdm
    - role: i3wm
      tags: i3wm
