---
# Playbook: desktop environment
# This will configure X, i3 and all the apps necessary

- import_playbook: base_confs.yml

- hosts: workstations
  ignore_unreachable: yes
  roles:
    - role: X11
      tags: 
        - X11
        - desktop
    - role: lightdm
      tags: 
        - lightdm
        - desktop
    - role: sway
      tags: 
        - sway
        - desktop
    - role: fonts
      tags: 
        - fonts
        - desktop
    - role: sound
      tags: sound
    - role: firefox
      tags: 
        - apps
        - firefox
    - role: slack
      tags: 
        - apps
        - slack
    - role: spotify
      tags: 
        - apps
        - spotify
    - role: telegram
      tags:
        - apps
        - telegram
    - role: zoom
      tags:
        - apps
        - zoom
    - role: packer
      tags:
        - dev
        - packer
    - role: python
      tags:
        - python
        - dev
    - role: aws
      tags:
        - dev
        - aws
    - role: elixir
      tags:
        - dev
        - elixir
    - role: docker
      tags:
        - docker
        - dev
    - role: k8s-utils
      tags:
        - k8s
        - dev
    - role: terraform
      tags:
        - terraform
        - dev
    - role: hugo
      tags:
        - hugo
        - dev
    - role: jetbrains
      tags:
        - jetbrains
        - dev
