#! /bin/bash

SSH_PVT_DEST=$HOME/.ssh/id_ed25519
SSH_PUB_DEST=$HOME/.ssh/id_ed25519.pub

BW_ITEM_ID=a1f215f0-ff3e-47a6-b505-ac830134fe79

if [[ ! $(bw unlock --check) ]]; then
  export BW_SESSION=$(bw unlock --raw)
fi

echo "Syncing Bitwarden Vault"
if [[ ! $(bw sync) ]]; then
  echo "Failed to sync Bitwarden. Abort"
  exit 1
fi

echo "Getting keys from Bitwarden"
bw get username "${BW_ITEM_ID}" > "${SSH_PUB_DEST}"
bw get password "${BW_ITEM_ID}" | base64 -d > "${SSH_PVT_DEST}"

