---
- name: "Add packer repo key to apt"
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
  become: yes

- name: "Add packer repository to apt"
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com buster main"
    state: present
  become: yes

- name: "Install packer"
  apt:
    pkg: packer
    state: present
    install_recommends: no
  become: yes
