---
base_packages:
- acpi
- sudo
- curl
- wget
- aptitude
- git
- python3-venv
- python3-dev
- unzip
- vim
- dnsutils
- u2f-host

debian_release: "buster"
username: "elacava"
#base_groups: 
#  - sudo
ssh_key_name: "id_ed25519"
