---
homebrew_installed_packages:
  - wget
  - curl
  - git
  - unzip
  - vim
  - tree
  - htop

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker

