---
# Install awscli from tarball

- name: "Create tmp folder"
  tempfile:
    state: directory
    suffix: temp
  register: awscli_tmp_folder

- name: "Download awscli"
  get_url:
    url: "{{ awscli_url }}"
    dest: "{{ awscli_tmp_folder.path }}/awscli.zip"
    checksum: "{{ awscli_sha256 }}"

- name: "Unpack awscli"
  unarchive:
    src: "{{ awscli_tmp_folder.path }}/awscli.zip"
    dest: "{{ awscli_tmp_folder.path}}"

- name: "Install awscli"
  command: "{{ awscli_tmp_folder.path }}/aws/install --update"
  become: yes

- name: "Cleanup"
  file:
    path: "{{ awscli_tmp_folder.path }}"
    state: absent
  when: awscli_tmp_folder.path is defined
