---
- name: "Create tmp folder"
  tempfile:
    state: directory
    suffix: temp
  register: zoom_tmp

- name: "Download zoom"
  get_url: 
    url: "https://zoom.us/client/latest/zoom_amd64.deb"
    dest: "{{ zoom_tmp.path }}/zoom.deb"
    checksum: "sha256:2510c736bf9ddb0ea521d4ca3c37b9f0ccd97b343a9b14feb1d275dec95d9c9b"

- name: "Install zoom dependencies"
  apt:
    name: 
    - xdg-dbus-proxy
    - xdg-user-dirs-gtk
    state: present
  become: true

- name: "Install zoom package"
  apt:
    deb: "{{ zoom_tmp.path }}/zoom.deb"
    state: present
  become: true

- name: "Cleanup"
  file:
    path: "{{ zoom_tmp }}"
    state: absent

