---
# Download necessary assets

- name: "Create backgrounds directory"
  file:
    path: "{{ lightdm_bg_path }}"
    state: directory
  become: yes

- name: "Download background"
  get_url:
    url: "{{ lightdm_bg_parmitano_url }}"
    dest: "{{ lightdm_bg_path }}/parmitano.jpg"
    checksum: "{{ lightdm_bg_parmitano_sha256 }}"
  become: yes

- name: "Set lightdm background"
  lineinfile:
    path: "/etc/lightdm/lightdm-gtk-greeter.conf"
    regexp: '^background='
    line: "background=/usr/share/images/backgrounds/parmitano.jpg"
  become: yes
