---
- include_tasks: docker.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: docker-compose.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: installer_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"