- name: "Ensure ssh private key is present"
  stat:
    path: /home/{{ username }}/.ssh/{{ ssh_key_name}}
  register: stat_result

- name: "Ensure ssh public key is present"
  stat:
    path: /home/{{ username }}/.ssh/{{ ssh_key_name}}.pub
  register: stat_result
