---
- name: "Install vim"
  apt:
    pkg:
      - vim
    state: present
    install_recommends: no
  become: yes
  when: ansible_facts['os_family'] == "Debian"


- name: "Install vim"
  community.general.homebrew:
    name:
      - vim
    state: latest
    update_homebrew: yes
  when: ansible_facts['os_family'] == "Darwin"

- name: "Clean vim vundle"
  file:
    state: absent
    path: "{{ vim_vundle_path }}"

- name: "Install vim vundle"
  command: "git clone {{ vim_vundle_repo }} {{ vim_vundle_path}}"

- name: "Install vim vundle plugins"
  command: "vim +PluginInstall +qall"
