---
- name: "Install pulseaudio"
  apt:
    pkg:
      - pulseaudio
      - pavucontrol
    state: present
  become: true

- name: "Ensure the config folder is clean"
  file:
    path: "$HOME/.config/pulse"
    state: absent
